Repository WardAnalytics/WardGraph, pull requests merged in 2024-01, with the labels that each got.

#13 Configure github actions to PR and main merge
  .github/workflows/firebase-dev-hosting-merge.yml
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  firebase.json
Labels: ci/cd

#14 Code Organization, New Features, Bug Fixing
  src/components/Graph/Graph.tsx
  src/components/Graph/Hotbar/Hotbar.tsx
  src/components/Graph/Hotbar/index.tsx
  src/components/Graph/LandingPage/LandingPage.tsx
  src/components/Graph/TransactionTooltip.tsx
  src/components/Graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/Graph/graph_calculations.tsx
  src/templates/GraphTemplate.tsx
Labels: bug, documentation, enhancement

#22 New hotbar and bug fixing
  src/components/Graph/Graph.tsx
  src/components/Graph/Hotbar/Hotbar.tsx
  src/components/Graph/Hotbar/index.tsx
  src/components/Graph/LandingPage/LandingPage.tsx
  src/components/Graph/TransactionTooltip.tsx
  src/components/Graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/Graph/graph_calculations.tsx
  src/templates/GraphTemplate.tsx
Labels: bug, enhancement

#30 Images & Optimizations
  .env.example
  src/components/Graph/AnalysisWindow/Content/tabs/ExposureTab/ExposureView.tsx
  src/components/Graph/AnalysisWindow/Header/Header.tsx
  src/components/Graph/Graph.tsx
  src/components/Graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.css
  src/components/Graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.tsx
  src/components/Graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/common/EntityLogo.tsx
  vite.config.ts
Labels: bug, enhancement

#32 Improvements & Bugfixes
  src/components/Graph/Graph.tsx
  src/components/Graph/Legend/Legend.tsx
  src/components/Graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.css
  src/components/Graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.tsx
  src/components/Graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/Graph/graph_calculations.tsx
Labels: bug, enhancement

#35 Legend tweaks
  src/components/Graph/Graph.tsx
  src/components/Graph/Legend/Legend.tsx
Labels: enhancement

#36 Add tooltip to risk score
  src/components/Graph/AnalysisWindow/AnalysisWindow.tsx
  src/components/Graph/AnalysisWindow/Header/components/RiskIndicator.tsx
  src/components/Graph/Graph.tsx
Labels: enhancement

#39 Performance Fix + Minor Improvement
  src/components/Graph/AnalysisWindow/Content/tabs/ExposureTab/EntityView.tsx
  src/components/Graph/AnalysisWindow/Overview/Overview.tsx
  src/components/Graph/Graph.tsx
Labels: bug, enhancement

#43 Feature/embeded image and text
  index.html
  src/assets/banner-ward.png
  src/components/Graph/Graph.tsx
Labels: enhancement

#46 Tutorial Loading Screens, add new address feature, feedback form, telegram instead of Discord
  src/Routes.tsx
  src/components/Graph/AnalysisWindow/AnalysisWindow.tsx
  src/components/Graph/Graph.tsx
  src/components/Graph/Hotbar/Hotbar.tsx
  src/components/Graph/LandingPage/SearchBar.tsx
  src/components/Graph/NewAddressModal/NewAddressModal.tsx
  src/components/Graph/NewAddressModal/index.tsx
  src/components/Socials/Socials.tsx
  src/components/tutorial/Tutorial.tsx
  src/components/tutorial/TutorialPopup.tsx
  src/components/tutorial/TutorialStepCard.tsx
  src/types/hotKeys.tsx
  vite.config.ts
Labels: bug, enhancement

#45 Bugfix/center graph
  src/components/Graph/Graph.tsx
Labels: bug
