Repository WardAnalytics/WardGraph, pull requests merged in 2024-02, with the labels that each got.

#50 Add dynamic transitions and toggle button for modes
  src/components/Graph/AnalysisWindow/AnalysisWindow.tsx
  src/components/Graph/AnalysisWindow/Content/Content.tsx
  src/components/Graph/AnalysisWindow/Header/Header.tsx
  src/components/Graph/AnalysisWindow/Overview/Overview.tsx
Labels: bug, enhancement

#54 Sidebar + Banner
  src/components/Graph/Graph.tsx
  src/components/Graph/Hotbar/Hotbar.tsx
  src/components/Graph/Legend/Legend.tsx
  src/components/Graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/Graph/index.tsx
  src/components/Graph/tutorial/Tutorial.tsx
  src/components/Graph/tutorial/TutorialPopup.tsx
  src/components/Graph/tutorial/TutorialStepCard.tsx
  src/components/banner/Banner.tsx
  src/components/banner/index.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/index.tsx
  src/hooks/useAuthState.tsx
  src/services/auth/auth.services.ts
  src/templates/GraphTemplate.tsx
Labels: enhancement

#48 Feature/user-search-history
  src/components/Graph/Graph.tsx
  src/components/Graph/LandingPage/SearchHistoryPopover.tsx
  src/components/graph/hotbar/components/NewAddressModal.tsx
  src/components/graph/search_bar/SearchBar.tsx
  src/services/auth/auth.services.ts
  src/services/firebase/analytics/analytics.ts
  src/services/firebase/search-history/search-history.ts
  src/services/firebase/short-urls/short-urls.ts
  src/templates/GraphTemplate.tsx
  src/templates/RedirectShortUrl.tsx
  src/templates/RedirectTemplate.tsx
Labels: enhancement

#57 Add mobile warning
  src/App.tsx
  src/templates/MobileWarningTemplate.tsx
  src/templates/index.tsx
Labels: enhancement

#60 Entity Search
  src/api/labels/labels.ts
  src/api/model/index.ts
  src/api/model/label.ts
  src/api/model/searchLabels200.ts
  src/api/model/searchLabelsBody.ts
  src/api/transactions/transactions.ts
  src/api/ward-analytics-api.yml
  src/components/graph/search_bar/SearchBar.tsx
  src/components/graph/search_bar/SearchHistoryPopover.tsx
  src/components/graph/search_bar/SearchResultPopover.tsx
  src/services/firebase/search-history/search-history.ts
Labels: enhancement

#61 Address Tags Rework
  package.json
  src/App.tsx
  src/components/common/Badge.tsx
  src/components/graph/Graph.tsx
  src/components/graph/analysis_window/AnalysisWindow.tsx
  src/components/graph/analysis_window/header/Header.tsx
  src/components/graph/analysis_window/header/TagInput.tsx
  src/components/graph/analysis_window/header/TagsPopover.tsx
  src/components/graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/graph/hotbar/components/NewAddressModal.tsx
  src/components/graph/search_bar/SearchBar.tsx
  src/hooks/useAuthState.tsx
  src/services/auth/auth.services.ts
  src/services/firebase.ts
  src/services/firebase/analytics/analytics.ts
  src/services/firebase/firestore.ts
  src/services/firestore/analytics/analytics.ts
  src/services/firestore/graph/addresses/custom-tags.ts
  src/services/firestore/graph/short-urls.ts
  src/services/firestore/user/custom-tags.ts
  src/services/firestore/user/search-history.ts
  src/templates/GraphTemplate.tsx
  src/types/hotKeys.tsx
  yarn.lock
Labels: enhancement

#63 Allow sign in on PR urls
  .github/workflows/firebase-hosting-pull-request.yml
Labels: ci/cd

#65 Refactor tagging
  src/components/graph/Graph.tsx
  src/components/graph/analysis_window/header/Header.tsx
  src/components/graph/analysis_window/header/TagInput.tsx
  src/components/graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/graph/search_bar/SearchBar.tsx
  src/services/firestore/graph/addresses/custom-tags.ts
Labels: enhancement

#66 Bugfix/tagging rerender
  firebase.json
  src/components/graph/Graph.tsx
  src/components/graph/analysis_window/AnalysisWindow.tsx
  src/components/graph/analysis_window/header/Header.tsx
Labels: bug, enhancement

#67 Address Actions, Risk Vision, Undo/Redo, Bigger Label Search
  src/components/graph/Graph.tsx
  src/components/graph/analysis_window/header/Header.tsx
  src/components/graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.tsx
  src/components/graph/custom_elements/edges/TransfershipEdge/TransfershipEdge.tsx
  src/components/graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/graph/hotbar/Hotbar.tsx
  src/components/graph/search_bar/SearchBar.tsx
  src/components/graph/search_bar/SearchResultPopover.tsx
Labels: enhancement

#55 Feature/firebase enable payments
  .env.example
  .github/workflows/firebase-dev-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .gitignore
  package.json
  src/App.tsx
  src/PrivateApp.tsx
  src/components/auth/AuthDialog.tsx
  src/components/auth/AuthInput.tsx
  src/components/auth/ForgotPasswordForm.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/graph/Graph.tsx
  src/components/graph/analysis_window/Header.tsx
  src/components/graph/hotbar/Hotbar.tsx
  src/components/navbar/Navbar.tsx
  src/hooks/useAuthState.tsx
  src/services/auth/auth.errors.ts
  src/services/auth/auth.services.ts
  src/services/firestore/analytics/analytics.ts
  src/services/firestore/graph/addresses/custom-tags.ts
  src/services/firestore/user/custom-tags.ts
  src/services/firestore/user/premium.ts
  src/services/payments/payments.services.ts
  src/templates/BillingTemplate.tsx
  src/templates/GraphTemplate.tsx
  src/templates/index.tsx
  src/utils/colors/classes.tsx
  src/utils/colors/enum.tsx
  yarn.lock
Labels: enhancement

#71 Feature/google analytics events
  src/components/auth/AuthDialog.tsx
  src/components/graph/analysis_window/content/advanced/tabs/ExposureTab/EntityView.tsx
  src/components/graph/analysis_window/content/overview/Overview.tsx
  src/components/graph/analysis_window/content/transactions/Transactions.tsx
  src/components/graph/analysis_window/header/Header.tsx
  src/components/graph/analysis_window/header/TagInput.tsx
  src/components/graph/hotbar/Hotbar.tsx
  src/components/graph/hotbar/components/CreateGraphDialog.tsx
  src/components/graph/hotbar/components/ShareDialog.tsx
  src/components/graph/landing_page/LandingPage.tsx
  src/components/graph/search_bar/SearchBar.tsx
  src/components/graph/tutorial/Tutorial.tsx
  src/components/navbar/Navbar.tsx
  src/services/firestore/analytics/analytics.ts
  src/templates/BillingTemplate.tsx
Labels: enhancement

#75 Update SearchBar.tsx
  src/components/graph/search_bar/SearchBar.tsx
Labels: enhancement

#76 Feature/terms and conditions
  src/assets/WardAnalytics-Terms-and-Conditions.pdf
  src/components/footer/Footer.tsx
  src/components/footer/index.ts
  src/components/footer/socials/Socials.css
  src/components/footer/socials/Socials.tsx
  src/components/footer/socials/index.tsx
  src/components/footer/terms_and_conditions/TermsAndConditions.tsx
  src/components/footer/terms_and_conditions/index.ts
  src/components/graph/Graph.tsx
Labels: documentation

#78 add robots.txt and sitemap, replace anchor tags for button tags and a…
  index.html
  package.json
  public/robots.txt
  public/sitemap.xml
  src/assets/ward-logo-icon-blue.png
  src/components/auth/SignInWithGoogleButton.tsx
  src/components/banner/Banner.tsx
  src/components/common/Logo.tsx
  src/components/common/RiskIndicator.tsx
  src/components/graph/hotbar/Hotbar.tsx
  src/components/graph/landing_page/LandingPage.tsx
  src/templates/MobileWarningTemplate.tsx
  tailwind.config.js
  vite.config.ts
  yarn.lock
Labels: enhancement

#79 Feature/seo improvement
  package.json
  src/App.tsx
  src/components/common/Logo.tsx
  src/components/common/SEO.tsx
  src/templates/BillingTemplate.tsx
  src/templates/SavedGraphTemplate.tsx
  src/templates/SavedGraphsTemplate.tsx
  src/templates/UnsavedGraphTemplate.tsx
  yarn.lock
Labels: enhancement

#80 Feature/seo improvement
  .github/workflows/firebase-dev-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  public/security.txt
Labels: enhancement

#83 Fit view on new addresses
  src/components/graph/Graph.tsx
Labels: enhancement

#84 Add walking circle animations to edges
  src/components/graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.css
  src/components/graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.tsx
  src/components/graph/custom_elements/edges/TransfershipEdge/TransfershipEdge.tsx
Labels: enhancement

#85 Zoom in / out actions + Trackpad/Mouse Settings
  src/components/graph/Graph.tsx
  src/components/graph/TransactionTooltip.tsx
  src/components/graph/analysis_window/header/Header.tsx
  src/components/graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.tsx
  src/components/graph/custom_elements/edges/TransfershipEdge/TransfershipEdge.tsx
  src/components/graph/hotbar/Hotbar.tsx
  src/components/graph/hotbar/components/SettingsDialog.tsx
Labels: enhancement

#82 My Graphs Features and Tutorial update
  src/App.tsx
  src/PublicApp.tsx
  src/components/auth/AuthInput.tsx
  src/components/common/CreateGraphDialog.tsx
  src/components/graph/Graph.tsx
  src/components/graph/analysis_window/content/transactions/Transactions.tsx
  src/components/graph/hotbar/components/CreateGraphDialog.tsx
  src/components/graph/search_bar/SearchBar.tsx
  src/components/graph/tutorial/ShowTutorialPopup.tsx
  src/components/graph/tutorial/TutorialDialog.tsx
  src/components/graph/tutorial/steps/TutorialSteps.tsx
  src/components/navbar/Navbar.tsx
  src/templates/BillingTemplate.tsx
  src/templates/RedirectShortUrl.tsx
  src/templates/SavedGraphsTemplate.tsx
Labels: enhancement

#86 Update password restrictions
  src/App.tsx
  src/components/auth/SignupForm.tsx
Labels: enhancement

#87 Deploy dev env on main merge
  .github/workflows/firebase-dev-hosting-merge.yml
Labels: ci/cd
