Repository WardAnalytics/WardGraph, pull requests merged in 2024-03, with the labels that each got.

#90 Fixed currency logos url
  src/components/common/EntityLogo.tsx
Labels: enhancement

#91 Revert "Improvement/refactor firebase files"
  index.html
  src/App.tsx
  src/components/auth/AuthInput.tsx
  src/components/auth/AuthInputCombobox.tsx
  src/components/auth/AuthInputSelect.tsx
  src/components/auth/SignupForm.tsx
  src/components/common/Combobox.tsx
  src/components/common/Listbox.tsx
  src/components/premium/WithPremium.tsx
  src/components/user_details/UserDetailsDialog.tsx
  src/components/user_details/UserDetailsForm.tsx
  src/components/user_details/UserDetailsInput.tsx
  src/components/user_details/UserDetailsInputSelect.tsx
  src/components/user_details/index.tsx
  src/hooks/useAuthState.tsx
  src/services/auth/auth.services.ts
  src/services/firestore/user/user.ts
  src/templates/BillingTemplate.tsx
  src/templates/RedirectShortUrl.tsx
  src/templates/SavedGraphsTemplate.tsx
  src/templates/UnsavedGraphTemplate.tsx
  src/utils/countries/countries.ts
  src/utils/roles/roles.ts
Labels: enhancement

#93 Bugfix/currencies icons
  src/components/common/EntityLogo.tsx
  src/components/common/TokenLogo.tsx
  src/components/graph/analysis_window/content/transactions/Transactions.tsx
Labels: enhancement

#92 Transactions between dialog
  src/api/transactions/transactions.ts
  src/components/common/Modal.tsx
  src/components/graph/Graph.tsx
  src/components/graph/TransactionTooltip.tsx
  src/components/graph/TransactionsBetweenAddressesDialog.tsx
  src/components/graph/custom_elements/edges/TransfershipEdge/CustomEdgePath.tsx
  src/components/graph/custom_elements/edges/TransfershipEdge/TransfershipEdge.tsx
Labels: enhancement

#96 Rework routing
  src/App.tsx
  src/PrivateApp.tsx
  src/PublicApp.tsx
  src/components/common/CreateGraphDialog.tsx
  src/components/graph/Graph.tsx
  src/components/graph/custom_elements/nodes/AddressNode/AddressNode/AddressNode.tsx
  src/components/graph/hotbar/Hotbar.tsx
  src/components/graph/hotbar/components/CreateGraphDialog.tsx
  src/components/graph/hotbar/components/ShareDialog.tsx
  src/components/navbar/Navbar.tsx
  src/routes/RoutesList.tsx
  src/routes/index.ts
  src/services/firestore/user/graph_saving/graph_saving.tsx
  src/templates/SavedGraphsTemplate.tsx
  src/templates/UnsavedGraphTemplate.tsx
  src/templates/index.tsx
Labels: bug, enhancement

#95 Yearly subscription
  .github/workflows/firebase-dev-hosting-merge.yml
  .github/workflows/firebase-hosting-merge.yml
  .github/workflows/firebase-hosting-pull-request.yml
  src/components/premium/PlansList.tsx
  src/components/premium/SubscriptionPeriodToggle.tsx
  src/templates/BillingTemplate.tsx
Labels: enhancement

#98 Automatically collect taxes
  src/services/stripe/payments.tsx
Labels: enhancement

#100 subscription price changed to 10€/month
  src/components/premium/SubscriptionPeriodToggle.tsx
Labels: enhancement

#101 Change the yearly value from 96€ per month to 8€ per month
  src/components/premium/SubscriptionPeriodToggle.tsx
Labels: bug
